### ISSUE TITLE
HW 1

### ISSUE THREAD

**Issue by ghost** [ualbany-csi402-s19/exercises#1]
Hello Professor,

I've been looking for Assignment one that's due Friday but I can't find it. Where should I look for all assignments?

Thank you!
Abby Abraham

**Comment by archx0r** [comment]
Hi Abby,

HW01 will be very simple and would be mostly related to Git concepts that we cover on Tuesday. I'll release it by tomorrow. But the expectation is that you can quickly take care of it after Tuesday session. We'll release future programming homeworks earlier.

--Amir

**Comment by ghost** [comment]
Thank you so much Professor!
